config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'articles#index'

  devise_for :users
  resources :users, only: [:index, :show, :new]
  post 'create_user', to: 'users#create', as: 'create_user'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :description
  belongs_to :user
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :sub_tags

  def self.like(filter)
    result = []
    Article.all.each do |article|
      result << article.id if article.match?(filter)
    end
    Article.where(id: result)
  end

  def match?(filter)
    filter = filter.downcase
    self.title.downcase.include?(filter) ||
        self.description.downcase.include?(filter) ||
        (self.try(:user).try(:name) && self.try(:user).try(:name).downcase.include?(filter)) ||
        self.tags.any?{|t|t.name.downcase.include?(filter)} ||
        self.sub_tags.any?{|st| st.name.downcase.include?(filter)}
  end
end

app/models/sub_tag.rb
class SubTag < ApplicationRecord
  validates_presence_of :name, :tag_id
  belongs_to :tag
  has_and_belongs_to_many :articles
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name
  has_many :sub_tags
  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :email, :password

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :set_article, only: [:show]
  before_action :set_tag_and_sub_tag_collection, only: [:new, :create]

  def index
    article_scope = Article.order(created_at: :desc)
    article_scope = article_scope.like(params[:filter]) if params[:filter]
    @articles = smart_listing_create(:articles, article_scope, partial: "articles/listing")
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id, {tag_ids:[]}, {sub_tag_ids:[]})
  end

  def set_tag_and_sub_tag_collection
    @tags = Tag.all.collect{|t| [t.name, t.id]}
    @sub_tags = SubTag.all.collect{|st| [st.name, st.id]}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

    <% if @article.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @article.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
      <%=f.error_span(:title) %>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_area :description, :class => 'form-control' %>
      </div>
      <%=f.error_span(:description) %>
    </div>

    <div class="form-group">
      <%= f.label :tags, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select(:tag_ids, Tag.all.collect {|t| [ t.name, t.id ] }, {}, { :multiple => true, :size => 5 }) %>
      </div>
      <%=f.error_span(:tag_ids) %>
    </div>

    <div class="form-group">
      <%= f.label :sub_tags, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select(:sub_tag_ids, SubTag.all.collect {|st| [ st.name, st.id ] }, {}, { :multiple => true, :size => 5 }) %>
      </div>
      <%=f.error_span(:sub_tag_ids) %>
    </div>
    <div>
      <%= f.hidden_field :user_id, value: user_signed_in? ? current_user.id : nil %>
    </div>





    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    articles_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/articles/_listing.html.erb
    <%- model_class = Article -%>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:title) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:author) %></th>
        <th><%= model_class.human_attribute_name(:published) %></th>
        <th><%= model_class.human_attribute_name(:tags) %></th>
        <th><%= model_class.human_attribute_name(:sub_tags) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
      </thead>
      <tbody>
      <% smart_listing.collection.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= article.try(:user).try(:name) %></td>
            <td><%= article.created_at.to_formatted_s(:short) %></td>
            <td><%= article.tags.pluck(:name).join(', ') %></td>
            <td><%= article.sub_tags.pluck(:name).join(', ') %></td>
            <td>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          article_path(article), :class => 'btn btn-default btn-xs' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= smart_listing.paginate %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="col-md-4 col-md-offset-4">
  <%= smart_listing_controls_for(:articles, {class: 'form-inline text-right'}) do %>
      <div class=" input-group">
        <%= text_field_tag :filter, '', class: 'search form-control', placeholder: 'Search...', autocomplete: :off %>

        <span class="input-group-btn">
            <%= button_tag class: 'btn btn-primary', data: {disable_with: '<i class="fa fa-spinner fast-spin" aria-hidden="true"></i>'} do -%>
              <i class="fa fa-search" aria-hidden="true"></i>
            <% end -%>
          </span>
      </div>
  <% end %>

</div>
<%= smart_listing_render(:articles) %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/index.js.erb
<%= smart_listing_update(:articles) %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @article.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @article.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @article.try(:user).try(:name) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @article.tags.pluck(:name).join(', ') %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sub_tags) %>:</strong></dt>
  <dd><%= @article.sub_tags.pluck(:name).join(', ') %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn btn-default'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Magazine' %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', :media => 'all' %>



  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Magazine</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Articles', articles_path %></li>

        <% if user_signed_in? %>
            <li><%= link_to current_user.email, current_user %></li>
            <li class="right"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %>
        <% end %>

      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer style="text-align: center">
    <p>&copy; Homify 2017</p>
  </footer>

</div> <!-- /container -->
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user,url: create_user_path(@user), :html => { :class => 'form-horizontal user'} do |f| %>

    <% if @user.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :email, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :email, :class => 'form-control' %>
      </div>
      <%=f.error_span(:email) %>
    </div>
    <div class="form-group">
      <%= f.label :password, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.password_field :password, :class => 'form-control' %>
      </div>
      <%=f.error_span(:password) %>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    users_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>